from __future__ import annotations

from typing import Any

MODEL_PROFILES = {
    "FAST_CHEAP",
    "DEEP_REASONING",
    "CODE_SPECIALIST",
    "CREATIVE_COPY",
    "WEB_RESEARCH",
    "DATA_ANALYST",
}


def _cat(
    cat_id: str,
    name: str,
    when_to_use: str,
    required_questions: list[str],
    primary: str,
    alternatives: list[str],
    prompt_template: str,
    output_type: str,
    next_action_rules: list[str],
) -> dict[str, Any]:
    return {
        "id": cat_id,
        "name": name,
        "when_to_use": when_to_use,
        "required_questions": required_questions,
        "model_profile_primary": primary,
        "model_profile_alternatives": alternatives,
        "prompt_template": prompt_template,
        "output_format_spec": {"type": output_type},
        "next_action_rules": next_action_rules,
    }


STUCK_CATEGORIES: list[dict[str, Any]] = [
    _cat(
        "doc_intro_weak",
        "문서 도입부가 안 써짐(설득 약함)",
        "문서의 첫 문단/도입이 막힐 때",
        ["독자/의사결정자는 누구인가?", "핵심 메시지 1문장은?", "반드시 넣을 근거/수치는?"],
        "DEEP_REASONING",
        ["CREATIVE_COPY", "FAST_CHEAP"],
        (
            "너는 B2B 기획서 작성 전문가다. 아래 정보를 바탕으로 도입부 2단락 3안을 작성하라.\n"
            "- 문서 목적: {goal}\n- 독자: {audience}\n- 핵심 메시지: {core_message}\n- 근거/수치: {evidence}\n"
            "제약: 과장 금지, 600자 이내, 각 안마다 한 문장 요약 포함.\n"
            "마지막에 수정 포인트 3개와 5분 행동 1개를 제시해라."
        ),
        "drafts",
        ["3안 중 1개 선택", "수정포인트 1개 즉시 반영", "5분: 첫 문단 붙여넣기"],
    ),
    _cat(
        "scope_ambiguous",
        "요구사항/범위가 모호함",
        "문제 정의와 비목표가 헷갈릴 때",
        ["문제/사용자는?", "성공 기준은?", "제외 범위는?"],
        "DEEP_REASONING",
        ["FAST_CHEAP"],
        (
            "너는 PM이다. 아래 상황을 요구사항 정의서 1페이지로 정리하라.\n"
            "상황: {stuck_text}\n산출: 문제정의/목표/비목표/핵심요구사항(우선순위)/가정/리스크/오픈이슈(질문 5개).\n"
            "모호한 부분은 가정을 명시하고 질문으로 전환하라. 마지막에 체크박스 3개 + 5분 행동 1개."
        ),
        "checklist",
        ["오픈이슈 1개 담당자에게 전송", "핵심요구사항 Top3 확정", "5분: 비목표 한 줄 작성"],
    ),
    _cat(
        "schedule_estimation",
        "일정 산정/마일스톤 막힘",
        "개발 일정과 버퍼 계산이 어려울 때",
        ["기능 목록은?", "팀 구성/속도는?", "데드라인은?"],
        "DEEP_REASONING",
        ["DATA_ANALYST"],
        (
            "너는 소프트웨어 프로젝트 플래너다. 기능/리소스/제약으로 공격안과 보수안 2가지를 작성하라.\n"
            "산출: WBS(작업-기간-의존성), 리스크 5개, 크리티컬 패스, 버퍼 제안.\n"
            "마지막에 이번 주 5분 행동 1개."
        ),
        "table",
        ["공격/보수 중 1안 선택", "불확실한 작업 1개 30분 단위로 분해", "5분: 의존성 1개 문서화"],
    ),
    _cat(
        "stakeholder_persuasion",
        "이해관계자 설득/반대 대응",
        "의사결정자 반대 논리 대응이 필요할 때",
        ["상대의 반대 논리는?", "상대 KPI는?", "양보 가능한 범위는?"],
        "DEEP_REASONING",
        ["CREATIVE_COPY"],
        "반대 논리 반박문, 양보안, 합의 초안 3안을 작성하고 회의 발화 스크립트를 60초 분량으로 제공하라.",
        "options",
        ["반박안 1개 선택", "양보선 1개 확정", "5분: 회의 첫 멘트 리허설"],
    ),
    _cat(
        "decision_paralysis",
        "의사결정(옵션 비교, 결정장애)",
        "A/B/C 옵션 중 결정이 안 될 때",
        ["옵션 A/B/C는?", "평가 기준은?", "가중치는?"],
        "DEEP_REASONING",
        ["FAST_CHEAP"],
        "결정 매트릭스(가중치 포함), 추천안, 리스크/완화책, 5분 행동 1개를 출력하라.",
        "table",
        ["가중치 3개 확정", "추천안 채택/보류 결정", "5분: 보류 리스크 1개 확인"],
    ),
    _cat(
        "meeting_ops",
        "회의 아젠다/회의록/액션아이템",
        "회의 전/후 정리가 막힐 때",
        ["회의 목적은?", "필수 결정 항목은?", "참석자는?"],
        "FAST_CHEAP",
        ["DEEP_REASONING"],
        "회의 아젠다(타임박싱), 결정 필요 항목, 회의 후 액션아이템 5개를 작성하라.",
        "checklist",
        ["아젠다 공유", "결정 항목 1개 사전 확인", "5분: 회의 목표 한 줄 공지"],
    ),
    _cat(
        "reply_tone_conflict",
        "이메일/메신저 답장(톤/갈등)",
        "답장 톤을 정하기 어려울 때",
        ["상대와 관계는?", "요청 목적은?", "강도(공손/단호)는?"],
        "CREATIVE_COPY",
        ["FAST_CHEAP"],
        "공손/단호/협상 3버전과 한 줄 요약, 보내기 전 체크리스트를 작성하라.",
        "drafts",
        ["버전 1개 선택", "수신자 맞춤 수정", "5분: 제목/첫 문장 확정"],
    ),
    _cat(
        "prd_structure",
        "PRD/기획서 구조가 안 잡힘",
        "PRD 섹션 구조를 잡기 어렵거나 빈칸이 많을 때",
        ["제품 목표는?", "핵심 사용자/시나리오는?", "MVP 범위는?"],
        "DEEP_REASONING",
        ["FAST_CHEAP"],
        "PRD 템플릿을 채우고 빈칸 질문을 생성하라. 마지막에 5분 행동: 섹션 헤더 붙여넣기.",
        "checklist",
        ["헤더 작성", "빈칸 질문 1개 해결", "5분: Problem 섹션 한 줄 작성"],
    ),
    _cat(
        "ux_flow_stuck",
        "UX 플로우/화면정의 막힘",
        "핵심 유저 플로우와 화면 목록이 정리되지 않을 때",
        ["핵심 사용자 목표는?", "시작/종료 상태는?", "에러 케이스는?"],
        "DEEP_REASONING",
        ["CREATIVE_COPY"],
        "핵심 유저 플로우 3개, 에러/엣지 케이스, 화면 리스트를 표로 정리하라.",
        "table",
        ["핵심 플로우 1개 고정", "에러 케이스 1개 추가", "5분: 화면 이름 5개 작성"],
    ),
    _cat(
        "kpi_definition",
        "KPI/지표 정의 막힘",
        "북극성 지표/입출력 지표를 정의할 때",
        ["비즈니스 목표는?", "사용자 행동 지표는?", "측정 주기는?"],
        "DEEP_REASONING",
        ["DATA_ANALYST"],
        "북극성 지표, 입력/출력 지표, 필요한 이벤트, 대시보드 목차를 작성하라.",
        "table",
        ["북극성 지표 1개 확정", "핵심 이벤트 3개 확정", "5분: 이벤트 1개 네이밍"],
    ),
    _cat(
        "tracking_plan",
        "이벤트 설계/트래킹 플랜",
        "analytics 이벤트 표준을 정리할 때",
        ["트리거 화면은?", "필수 속성은?", "QA 기준은?"],
        "DATA_ANALYST",
        ["DEEP_REASONING"],
        "이벤트명/트리거/속성/예시 payload와 QA 체크리스트를 작성하라.",
        "table",
        ["핵심 이벤트 3개 확정", "속성 스키마 정의", "5분: 이벤트 1개 payload 작성"],
    ),
    _cat(
        "privacy_copy",
        "리스크/법무/프라이버시 문구",
        "옵트인 문구와 최소수집 원칙 정리가 필요할 때",
        ["대상 기능은?", "수집 항목은?", "삭제/철회 경로는?"],
        "DEEP_REASONING",
        ["FAST_CHEAP"],
        "옵트인 문구, 최소수집 원칙, 사용자 권리(삭제/토글/회수) 안내 카피를 작성하라.",
        "drafts",
        ["문구안 1개 선택", "법무 리뷰 포인트 표시", "5분: 토글 설명 1줄 반영"],
    ),
    _cat(
        "market_research",
        "경쟁사/시장 조사(최신 필요)",
        "최신 정보/출처 기반 비교가 필요할 때",
        ["조사 범위는?", "비교 축은?", "의사결정 질문은?"],
        "WEB_RESEARCH",
        ["DEEP_REASONING"],
        "웹 리서치 계획, 출처 기반 요약, 비교표, 결론/추천을 작성하라.",
        "table",
        ["비교축 3개 확정", "출처 2개 수집", "5분: 경쟁사 1개 핵심강점 기록"],
    ),
    _cat(
        "slide_storyline",
        "슬라이드 아웃라인/스토리라인",
        "발표 자료 구조와 메시지 연결이 약할 때",
        ["청중은?", "발표 목적은?", "핵심 결론은?"],
        "CREATIVE_COPY",
        ["FAST_CHEAP"],
        "슬라이드 10장 구성, 장당 메시지 1줄, 도표 아이디어를 작성하라.",
        "options",
        ["스토리라인 1안 선택", "장표 3개 우선 작성", "5분: 제목 슬라이드 완성"],
    ),
    _cat(
        "copy_naming",
        "카피 변형/네이밍/브랜딩",
        "메시지 변형과 이름 후보가 필요할 때",
        ["브랜드 톤은?", "타깃은?", "금지어는?"],
        "CREATIVE_COPY",
        ["DEEP_REASONING"],
        "컨셉 3개, 후보 20개, 필터 기준을 제시하라.",
        "options",
        ["후보 3개 shortlist", "필터 1회 적용", "5분: 팀 공유 메시지 작성"],
    ),
    _cat(
        "debug_error",
        "코드 디버깅(에러/스택트레이스)",
        "원인 파악과 재현/수정이 막힐 때",
        ["에러 로그는?", "기대 동작은?", "환경은?"],
        "CODE_SPECIALIST",
        ["DEEP_REASONING"],
        "원인 후보 3개, 확인 절차, 수정 패치안을 순서대로 작성하라.",
        "checklist",
        ["원인 후보 1개 검증", "재현 조건 기록", "5분: 최소 재현 코드 만들기"],
    ),
    _cat(
        "refactor_perf",
        "리팩토링/성능 최적화",
        "병목 추정은 되나 실행안이 없을 때",
        ["병목 지점은?", "현재 지표는?", "허용 리스크는?"],
        "CODE_SPECIALIST",
        ["DEEP_REASONING"],
        "병목 추정, 측정 계획, 변경 최소 패치, 롤백 계획을 작성하라.",
        "checklist",
        ["측정 지표 1개 선택", "패치 범위 축소", "5분: 벤치마크 스크립트 실행 준비"],
    ),
    _cat(
        "data_cleanup_calc",
        "데이터 정리/표 만들기/계산",
        "컬럼/계산식/검증 규칙이 헷갈릴 때",
        ["원본 데이터 구조는?", "목표 표는?", "검증 기준은?"],
        "DATA_ANALYST",
        ["FAST_CHEAP"],
        "필요한 컬럼, 계산식, 검증 단계, 결과 표 형식을 제시하라.",
        "table",
        ["컬럼 5개 확정", "계산식 1개 검증", "5분: 샘플 10행 정리"],
    ),
    _cat(
        "writing_structure",
        "글이 산만함(논리/구조 재정리)",
        "문장이 길고 핵심이 흐려질 때",
        ["핵심 주장 1문장은?", "현재 목차는?", "독자 수준은?"],
        "FAST_CHEAP",
        ["DEEP_REASONING"],
        "핵심 주장 1문장, 목차 재구성, 문장 다듬기 규칙을 제시하라.",
        "checklist",
        ["핵심 주장 확정", "목차 재배열", "5분: 첫 섹션 3문장 재작성"],
    ),
    _cat(
        "can_not_start",
        "작업 착수 자체가 안 됨(불안/피곤/압도)",
        "할 일을 알아도 시작이 안 될 때",
        ["지금 가장 부담되는 것은?", "마감은?", "에너지 상태는?"],
        "DEEP_REASONING",
        ["FAST_CHEAP"],
        (
            "너는 생산성 코치다. 상황을 5분 착수 플랜으로 바꿔라.\n"
            "산출: 최소 단위 3개, 장벽 제거 2개, 무조건 가능한 5분 행동 1개.\n"
            "톤: 부드럽고 단정."
        ),
        "checklist",
        ["최소단위 1개 선택", "장벽 제거 1개 실행", "5분 행동 즉시 시작"],
    ),
    _cat(
        "priority_conflict",
        "요구사항 충돌/우선순위 싸움",
        "서로 다른 이해관계자 요구가 충돌할 때",
        ["충돌 항목은?", "각 이해관계자 목표는?", "마감/제약은?"],
        "DEEP_REASONING",
        ["FAST_CHEAP"],
        "요구사항 충돌을 영향도/긴급도 기준으로 우선순위 표로 정리하고 합의안을 제시하라.",
        "table",
        ["우선순위 규칙 합의", "보류 항목 명시", "5분: 보류 사유 공지 작성"],
    ),
    _cat(
        "qa_testcases",
        "QA/테스트 케이스 설계 막힘",
        "테스트 범위와 케이스 분류가 안 될 때",
        ["기능 범위는?", "리스크 높은 경로는?", "승인 기준은?"],
        "CODE_SPECIALIST",
        ["DATA_ANALYST"],
        "정상/예외/경계 테스트 케이스와 우선순위를 표로 만들고 smoke set를 제안하라.",
        "table",
        ["Smoke 5개 선정", "경계값 1개 추가", "5분: 첫 테스트 케이스 작성"],
    ),
    _cat(
        "release_note",
        "릴리즈 노트/공지 작성",
        "변경사항 공지 문구가 정리되지 않을 때",
        ["대상 사용자층은?", "핵심 변경점은?", "주의사항은?"],
        "FAST_CHEAP",
        ["CREATIVE_COPY"],
        "릴리즈 노트(요약/변경점/영향/주의사항/문의채널) 템플릿과 공지 2버전을 작성하라.",
        "drafts",
        ["버전 1개 채택", "주의사항 1개 강조", "5분: 배포 채널용 한 줄 공지"],
    ),
    _cat(
        "prep_summary",
        "문서 요약/회의 준비",
        "긴 문서를 빠르게 요약하고 회의 준비가 필요할 때",
        ["문서 길이/형식은?", "회의 목적은?", "결정 포인트는?"],
        "FAST_CHEAP",
        ["DEEP_REASONING"],
        "핵심 요약, 논점 5개, 회의 질문 5개, 의사결정 포인트를 작성하라.",
        "checklist",
        ["질문 2개 선택", "결정 포인트 확인", "5분: 오프닝 멘트 작성"],
    ),
    _cat(
        "request_message",
        "상대방에게 요청 메시지(부탁/재촉)",
        "도움 요청이나 일정 재촉 메시지가 어려울 때",
        ["상대와 관계는?", "요청 마감은?", "톤은?"],
        "CREATIVE_COPY",
        ["FAST_CHEAP"],
        "부탁형/재촉형/협상형 메시지 3안과 후속 메시지 타이밍 가이드를 제시하라.",
        "options",
        ["메시지 1안 선택", "마감 명시", "5분: 발송 전 1회 검토"],
    ),
]


def choose_category(stuck_text: str, desired_output: str) -> dict[str, Any]:
    haystack = f"{stuck_text}\n{desired_output}".lower()

    keyword_map = [
        ("에러", "debug_error"),
        ("stack", "debug_error"),
        ("디버", "debug_error"),
        ("리팩", "refactor_perf"),
        ("성능", "refactor_perf"),
        ("일정", "schedule_estimation"),
        ("마일스톤", "schedule_estimation"),
        ("요구사항", "scope_ambiguous"),
        ("스코프", "scope_ambiguous"),
        ("설득", "stakeholder_persuasion"),
        ("반대", "stakeholder_persuasion"),
        ("결정", "decision_paralysis"),
        ("회의", "meeting_ops"),
        ("이메일", "reply_tone_conflict"),
        ("메신저", "reply_tone_conflict"),
        ("prd", "prd_structure"),
        ("ux", "ux_flow_stuck"),
        ("kpi", "kpi_definition"),
        ("트래킹", "tracking_plan"),
        ("개인정보", "privacy_copy"),
        ("프라이버시", "privacy_copy"),
        ("경쟁", "market_research"),
        ("시장", "market_research"),
        ("슬라이드", "slide_storyline"),
        ("카피", "copy_naming"),
        ("네이밍", "copy_naming"),
        ("qa", "qa_testcases"),
        ("테스트", "qa_testcases"),
        ("릴리즈", "release_note"),
        ("공지", "release_note"),
        ("요약", "prep_summary"),
        ("부탁", "request_message"),
        ("재촉", "request_message"),
        ("시작", "can_not_start"),
        ("불안", "can_not_start"),
    ]
    for keyword, cat_id in keyword_map:
        if keyword in haystack:
            return next(cat for cat in STUCK_CATEGORIES if cat["id"] == cat_id)
    return STUCK_CATEGORIES[0]

